// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8HUwb5eUEyoVOb4ohCbZKBR1k1GJwuxI',
    appId: '1:107009486005:web:8373574dc117c51aef22fc',
    messagingSenderId: '107009486005',
    projectId: 'study-share-6a211',
    authDomain: 'study-share-6a211.firebaseapp.com',
    storageBucket: 'study-share-6a211.firebasestorage.app',
    measurementId: 'G-YESFT6FD62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkn958UI2BQZWSgro3IE8xAk0m82-1H38',
    appId: '1:107009486005:android:3cf56abd987a9158ef22fc',
    messagingSenderId: '107009486005',
    projectId: 'study-share-6a211',
    storageBucket: 'study-share-6a211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5RSxAZV5lfeAchAc30fC0FVYy9oUGfk',
    appId: '1:107009486005:ios:9b5a83a4fd7b9332ef22fc',
    messagingSenderId: '107009486005',
    projectId: 'study-share-6a211',
    storageBucket: 'study-share-6a211.firebasestorage.app',
    iosBundleId: 'com.example.studySupport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE5RSxAZV5lfeAchAc30fC0FVYy9oUGfk',
    appId: '1:107009486005:ios:9b5a83a4fd7b9332ef22fc',
    messagingSenderId: '107009486005',
    projectId: 'study-share-6a211',
    storageBucket: 'study-share-6a211.firebasestorage.app',
    iosBundleId: 'com.example.studySupport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8HUwb5eUEyoVOb4ohCbZKBR1k1GJwuxI',
    appId: '1:107009486005:web:65ffe977ce4438a1ef22fc',
    messagingSenderId: '107009486005',
    projectId: 'study-share-6a211',
    authDomain: 'study-share-6a211.firebaseapp.com',
    storageBucket: 'study-share-6a211.firebasestorage.app',
    measurementId: 'G-NNGDZSL1SH',
  );
}
